version: "3.9"

services:
  backend:
    image: ghcr.io/elitehacker228/pe-2025-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: ghcr.io/elitehacker228/pe-2025-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=development