name: Run Backend Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Pytest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: backend
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        working-directory: backend
        shell: bash
        run: |
          source .venv/bin/activate
          pytest tests/ -v